version: '3.7'
services:
  simple-api-1:
    build: java/simple-api-with-db/
    container_name: simple-api-1
    networks:
      - network_tp01
    depends_on:
      - database

  simple-api-2:
    build: java/simple-api-with-db/
    container_name: simple-api-2
    networks:
      - network_tp01
    depends_on:
      - database

  database:
    build: database/
    container_name: postgresdb
    networks:
      - network_tp01
    volumes:
      - ./database/data:/var/lib/postgresql/data
    
  httpd:
    build: http/
    container_name: http_server
    ports:
      - '80:80'
    networks:
      - network_tp01
    depends_on:
      - backend
      - front

  front:
    build: front/
    container_name: front
    networks:
      - network_tp01

networks:
  network_tp01:
