---
# tasks file for roles/launch_proxy
- name: Create proxy container and connect to network
  docker_container:
    name: simple-api-with-db
    image: "adriengvd/tp-devops-cpe:simple-api"
    pull: true
    networks:
      - name: "network_tp3"