name: Build and push images
on:
  #the job is launched from the test_backend workflow
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    
jobs:
  build-and-push-database:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
    - name: Login to DockerHub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build image and push database
    # DO the same for database
      uses: docker/build-push-action@v2
      with: 
      # relative path to the place where source code with  Dockerfile is located
        context: ./database
        # Note: tags has to be all lower-case
        tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-cpe:database
        push: ${{github.ref == 'refs/heads/main'}}

  build-and-push-http:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
    - name: Login to DockerHub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build image and push httpd
    # DO the same for httpd
      uses: docker/build-push-action@v2
      with: 
      # relative path to the place where source code with  Dockerfile is located
        context: ./http
        # Note: tags has to be all lower-case
        tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-cpe:http-server
        push: ${{github.ref == 'refs/heads/main'}}

  build-and-push-front:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
    - name: Login to DockerHub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build image and push backend
      uses: docker/build-push-action@v2
      with: 
      # relative path to the place where source code with  Dockerfile is located
        context: ./java/front
        # Note: tags has to be all lower-case
        tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-cpe:front
        # build on feature branches, push only on main branch
        push: ${{github.ref == 'refs/heads/main'}}

  build-and-push-java:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
    - name: Login to DockerHub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build image and push backend
      uses: docker/build-push-action@v2
      with: 
      # relative path to the place where source code with  Dockerfile is located
        context: ./java/simple-api-with-db
        # Note: tags has to be all lower-case
        tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-cpe:simple-api
        # build on feature branches, push only on main branch
        push: ${{github.ref == 'refs/heads/main'}}

