name: Run ansible playbook
on:
  #the job is launched from the build_and_push_images workflow
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      SSH_KEY:
        required: true

jobs:
  run-playbook:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 requests
    - name: set ansible config secrets
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.SSH_KEY }}
      run: |
        mkdir .ssh
        echo "$SSH_KEY" > .ssh/id_rsa
        
    - name: run exporters playbook
      run: |
        ansible-playbook -i inventory playbook.yml