name: Run ansible playbook
on:
  #the job is launched from the build_and_push_images workflow
  workflow_call:
    secrets:
      SSH_KEY:
        required: true

jobs:
  run-playbook:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: ./ansible/playbook.yml
        # Optional, SSH private key
        key: ${{secrets.SSH_KEY}}
        # Optional, literal inventory file contents
        inventory: |
          all:
            vars:
              ansible_user: centos
            children:
              prod:
                hosts: 
                  adrien.gervraud.takima.cloud:
